const GET_CAR_DETAILS_REQUEST = "GET_CAR_DETAILS_REQUEST";
const GET_CAR_DETAILS_SUCCESS= "GET_CAR_DETAILS_SUCCESS";
const GET_CAR_DETAILS_FAILED = "GET_CAR_DETAILS_FAILED";

export default {
    GET_CAR_DETAILS_REQUEST,
    GET_CAR_DETAILS_SUCCESS,
    GET_CAR_DETAILS_FAILED,
}